Kconfig: MXC_GPU_VIV: add depends/select as required
gpu viv cannot build without these, so declare proper requirements.

This fixes build failures such as a long list of messages like:
gc_hal_kernel_drm.c:(.text+0x720): undefined reference to `drm_gem_object_lookup'

Change-Id: I28d1f04607c2b485bf67ededf65048c85ba3ee5d
Signed-off-by: Dominique Martinet <dominique.martinet@atmark-techno.com>